### ISSUE TITLE
A bug about disable lid sleep in macOS 10.13

### ISSUE THREAD

**Issue by huanyujieji** [HsOjo/SleeperX#1]
My mac has the OS 13.0 system, and when I use the function which is called disable lid sleep, I can't use it at all.This is the issue that I met in the application.Thanks for your sharing.

**Comment by HsOjo** [comment]
Hello, I'm sorry. Because my development environment based on macOS 10.14, So I'm never do test this program on 10.13, maybe some problem existed.
Disable lid sleep actually implements by execute command ```sudo pmset -a disablesleep 1```, So you can try to execute this command on **Terminal.app**, If it can't disable sleep, then is **10.13 unsupported** this feature.

**Comment by huanyujieji** [comment]
OK，thank you very much.


| |
huangjiawei970
|
|
邮箱：huangjiawei970@163.com
|

Signature is customized by Netease Mail Master

On 08/03/2019 03:56, HsOjo wrote:

Hello, I'm sorry. Because my development environment based on macOS 10.14, So I'm never do test this program on 10.13, maybe some problem existed.
Disable lid sleep actually execute command "sudo pmset -a disablesleep 1" to implements, So you can try to execute this command on "Terminal.app", If it can't disable sleep, then is 10.13 unsupported this feature.
